/* 
 * Copyright 2018 by RADical Information Design Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
package com.radinfodesign.fboace.service;
/*
 *  Generated by RADSpringBootGen from ServiceTemplate.java.txt
*/  

import com.radinfodesign.fboace.model.Aircraft;
import java.util.List;

public interface AircraftService {

  List<Aircraft> getAll();
  
  Aircraft getEntity (Integer aircraftId);
  
  Aircraft putEntity 
      ( Integer aircraftId
      , String shortName
      , String longName
      , String description
      , String notes
      , Integer aircraftTypeId
      ) throws Exception;
  
  int deleteEntity(Integer aircraftId);

  
      
}
