/* 
 * Copyright 2018 by RADical Information Design Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
package com.radinfodesign.fboace.service;
/*
 *  Generated by RADSpringBootGen from ServiceTemplate.java.txt
*/  

import com.radinfodesign.fboace.model.Flight;
import com.radinfodesign.fboace.model.Pilot;
import java.util.List;

public interface FlightService {

  List<Flight> getAll();
  
  Flight getEntity (Integer flightId);
  
  Flight putEntity 
      ( Integer flightId
      , String shortName
      , String longName
      , String departureDateTime
      , String arrivalDateTime
      , String notes
      , Integer aircraftId
      , Integer airportIdDeparture
      , Integer airportIdDestination
      , String[] flightCrewMemberNotess
      , Integer[] flightCrewMemberPilotIds
      ) throws Exception;
  
  int deleteEntity(Integer flightId);

  int deleteFlightCrewMember 
                  ( Integer flightCrewMemberFlightId
                  , Integer flightCrewMemberPilotId
                  );
  
  List<Flight> getQualifiedFlightsByPilotId (Integer pilotId);
      
}
