/* 
 * Copyright 2018 by RADical Information Design Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/
package com.radinfodesign.fboace.service;
/*
 *  Generated by RADSpringBootGen from ServiceTemplate.java.txt
*/  

import com.radinfodesign.fboace.model.Pilot;
import com.radinfodesign.fboace.model.AircraftType;
import com.radinfodesign.fboace.model.Flight;
import java.util.List;

public interface PilotService {

  List<Pilot> getAll();
  
  Pilot getEntity (Integer pilotId);
  
  Pilot putEntity 
      ( Integer pilotId
      , String lastName
      , String firstName
      , String middleInitial
      , String nationalIdNumber
      , String birthdate
      , String notes
      , String[] pilotCertificationCertificationNumbers
      , String[] pilotCertificationValidFromDates
      , String[] pilotCertificationExpirationDates
      , String[] pilotCertificationNotess
      , Integer[] pilotCertificationAircraftTypeIds
      , String[] flightCrewMemberNotess
      , Integer[] flightCrewMemberFlightIds
      , String[] pilotRareThingShortNames
      , String[] pilotRareThingLongNames
      , String[] pilotRareThingNotess
      ) throws Exception;
  
  int deleteEntity(Integer pilotId);

  int deletePilotCertification 
                  ( Integer pilotCertificationPilotId
                  , Integer pilotCertificationAircraftTypeId
                  );
  int deleteFlightCrewMember 
                  ( Integer flightCrewMemberFlightId
                  , Integer flightCrewMemberPilotId
                  );
                
  int deletePilotRareThing 
                  ( Integer pilotRareThingPilotId
                  );

  List<Pilot> getQualifiedPilotsByAircraftTypeId (Integer aircraftTypeId);
  List<Pilot> getQualifiedPilotsByFlightId (Integer flightId);
      
}
